docs: changes in documentation
harshalini/Linis-component-library pull request #1
Opened 2022-01-28 13:14 UTC by harshalini

2022-01-28 13:19 UTC, Raghav888 requested changes
Use rem , rest looks good

2022-01-28 13:19 UTC, Raghav888 commented on style.css
> +    margin: 100px 25px 0px 25px;
Use rem only if more than 10px.

2022-01-28 13:20 UTC, Manju-sree reviewed
looks pretty , try to add unique class-names with the name you choose for component library..

2022-01-28 13:35 UTC, merged

2022-01-28 13:48 UTC, tushartiwari7 commented
Code is good! 
But from next time try to make several small PR's instead of one huge PR.

2022-01-29 05:23 UTC, harshalini commented
> 

Yes, thanks for suggestion.